// controller.filterCategories
CFTEMPLATES.dataFiltersControlFooter = [
	'<div class="container-fluid">',
		'<div class="collapse navbar-collapse">',
			
			'<button type="button" class="navbar-btn btn btn-default btn-xs navbar-left cf-cancel-filter-set-changes-button">Cancel</button>',
			'<button type="button" class="navbar-btn btn btn-success btn-xs navbar-left cf-save-filter-set-changes-button">Done</button>',
			
			'<ul class="nav navbar-nav navbar-right">',
				'<li class="dropup btn btn-xs cf-save-filter-list" title="save">',
					'<a href="#" class="dropdown-toggle btn btn-xs" data-toggle="dropdown">',
						'<span class="glyphicon glyphicon-floppy-disk"></span>',
						'<span class="caret"></span>',
					'</a>',
					'<ul class="dropdown-menu" role="menu">',
						'<li data-save-type="__new_category__">',
							'<a href="#">',
								'<span class="badge pull-right">',
									'<span class="glyphicon glyphicon-plus"></span>',
								'</span> new category',
							'</a>',
						'</li>',
					'</ul>',
				'</li>',
			'</ul>',
			
			'<button type="button" class="close navbar-btn navbar-right cf-clear-all-filters-button disabled" disabled="disabled" title="clear all working filters">',
				'<span aria-hidden="true">&times;</span><span class="sr-only">Clear Filters</span>',
			'</button>',
			
		'</div>',
	'</div>',
	'<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="save category or filter set" aria-hidden="true">',
		'<div class="modal-dialog modal-lg">',
			'<div class="modal-content">',
				'<div class="modal-header">',
					'<button type="button" class="close" data-dismiss="modal">',
						'<span aria-hidden="true">&times;</span>',
						'<span class="sr-only">Cancel</span>',
					'</button>',
					'<h4 class="modal-title">Modal title</h4>',
				'</div>',
				'<div class="modal-body"></div>',
				'<div class="modal-footer">',
					'<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
					'<button type="button" class="btn btn-primary" data-save-type="category">Save</button>',
				'</div>',
			'</div>',
		'</div>',
	'</div>'
].join('');