/**
 * This template contains elements for the footer navigation control. This 
 * template is only rendered in CATEGORY_SETS and CATEGORIES_NO_TYPES modes.
 * @memberof $.fn.ColumnFilters
 * @constant {string} DATA_FILTERS_CONTROL_FOOTER_TEMPLATE
 * @property {object} config - the template object
 * @property {object[]} config.filters - 
 * @property {object[]} config.categories - 
 * @property {object[]} config.filtersets - 
 */
$.fn.ColumnFilters.FILTER_SAVE_CONTROL_VIEW_TEMPLATE = [
    '<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="save category or filter set" aria-hidden="true">',
        '<div class="modal-dialog modal-lg">',
            '<div class="modal-content">',
                '<div class="modal-header">',
                    '<button type="button" class="close" data-dismiss="modal">',
                        '<span aria-hidden="true">&times;</span>',
                        '<span class="sr-only">Cancel</span>',
                    '</button>',
                    '<h4 class="modal-title"></h4>',
                '</div>',
                '<div class="modal-body"></div>',
                '<div class="modal-footer">',
                    '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>',
                    '<button type="button" class="btn btn-primary" data-save-type="category">Save</button>',
                '</div>',
            '</div>',
        '</div>',
    '</div>',
	'<div class="container-fluid">',
	    '<div class="navbar-header">',
	        '<button class="navbar-toggle" data-target="#cf-filter-save-controls" data-toggle="collapse" type="button" aria-expanded="true">',
	            '<span class="glyphicon glyphicon-menu-hamburger"></span>',
	        '</button>',
	    '</div>',
		'<div id="cf-filter-save-controls" class="collapse navbar-collapse" aria-expanded="true">',
		    '<form class="navbar-form navbar-left">',
		        '<div class="form-group nav navbar-nav cf-fsc-save-filterset-buttongroup"<% if( config.controlMode!==$.fn.ColumnFilters.ControlModes.EDIT) { %> style="display:none"<% } %>>',
    		        '<fieldset>',
            		    '<div class="btn-group" role="group">',
            			    '<button type="button" class="btn btn-default btn-xs">Cancel</button>',
            			    '<button type="button" class="btn btn-success btn-xs">Done</button>',
            			'</div>',
            		'</fieldset>',
            	'</div>',
                '<% for(var i in config.categories) { ',
                'var hasFilters = _.has(config.filtersets, config.categories[i].name), ',
                    'filterset = hasFilters ? config.filtersets[config.categories[i].name] : false; %>',
                '<ul class="nav navbar-nav" data-category-id="<%= config.categories[i].cid %>">',
                    '<li class="dropup btn btn-xs<% if(!hasFilters) { %> disabled<% } %>">',
                        '<a class="dropdown-toggle btn btn-xs<% if( config.controlMode===$.fn.ColumnFilters.ControlModes.EDIT) { %> disabled<% } %>" data-toggle="dropdown" href="#" aria-expanded="false">',
                            '<%= config.categories[i].name %> ',
                            '<% if(hasFilters) { %>',
                            '<span class="badge"><%= filterset.length %></span>',
                            '<% } %>',
                        '</a>',
                        '<% if(hasFilters) { %>',
                        '<ul class="dropdown-menu list-group cf-fsc-filter-set-menu" role="menu"><% for(var j in filterset) { %>',
                            '<li class="list-group-item">',
                                '<button type="button" class="close cf-fsc-filter-set-edit-button" title="edit this filter set" data-id="<%= filterset[j].cid %>">',
                                    '<span class="glyphicon glyphicon-cog btn-sm"></span>',
                                '</button>',
                                '<button type="button" class="close cf-fsc-filter-set-remove-button" title="remove this filter set" data-id="<%= filterset[j].cid %>">',
                                    '<span class="glyphicon glyphicon-remove btn-sm"></span>',
                                '</button>',
                                '<h4 class="list-group-item-heading" title="load filters from this filter set">',
                                    '<a href="#" data-id="<%= filterset[j].cid %>"><%= filterset[j].name %></a>',
                                '</h4>',
                                '<p class="list-group-item-text"><%= filterset[j].description %></p>',
                            '</li>',
                        '<% } %></ul>',
                        '<% } %>',
                    '</li>',
                '</ul>',
                '<% } %>',
            	
        	'</form>',
        	'<form class="navbar-form navbar-right">',
        	    '<div class="form-group nav navbar-nav cf-fsc-clear-filterset-button">',
        		    '<button class="btn btn-danger btn-xs" type="button" title="clear all working filters"',
        		        '<% if(config.filters.length<1 || config.controlMode===$.fn.ColumnFilters.ControlModes.EDIT) { %> disabled="disabled"<% } %>',
        		    '>',
        		        '<span class="glyphicon glyphicon-remove"></span>',
        		    '</button>',
            	'</div>',
            	'<div class="col-sm-1"></div>',
            	'<div class="form-group nav navbar-nav cf-fsc-filter-category-menu">',
            		'<fieldset<% if(config.filters.length<1 || config.controlMode===$.fn.ColumnFilters.ControlModes.EDIT) { %> disabled="disabled"<% } %>>',
                        '<ul style="margin-bottom:0;padding-left:0">',
                            '<li class="dropup cf-save-filter-list-item" title="save">',
                                '<a href="#" class="dropdown-toggle btn btn-primary btn-xs" data-toggle="dropdown">',
                                    '<span class="glyphicon glyphicon-floppy-disk"></span>',
                                    '<span class="caret"></span>',
                                '</a>',
                                '<ul class="dropdown-menu" role="menu">',
                                    '<li data-category-index="0">',
                                        '<a href="#">',
                                            '<span class="badge pull-right">',
                                                '<span class="glyphicon glyphicon-plus"></span>',
                                            '</span> new category',
                                        '</a>',
                                    '</li>',
                                    '<% for(var i in config.categories) { %>',
                                    '<li data-category-index="<%= config.categories[i].cid %>">',
                                        '<a href="#">',
                                            '<span class="badge pull-right">',
                                                '<span class="glyphicon glyphicon-filter"></span>',
                                            '</span> <%= config.categories[i].name %>',
                                        '</a>',
                                    '</li>',
                                    '<% } %>',
                                '</ul>',
                            '</li>',
                        '</ul>',
                    '</fieldset>',
                '</div>',
			'</form>',
		'</div>',
	'</div>'
].join('');

